### ISSUE TITLE
Steam Achievements

### ISSUE THREAD

**Issue by TheIndiv** [nashmuhandes/BetterStrife#1]
When it comes to the Veteran Edition, would you have any idea if this breaks Steam's achievements?

**Comment by nashmuhandes** [comment]
I'm sorry, there appears to be a miscommunication (most likely my own fault). When I said that this was compatible with SVE, I meant that this is compatible with the SVE IWAD _when played with GZDoom_.

This mod is only for GZDoom and will never be runnable with Strife Veteran Editon on Steam.

I will make this correction soon. Apologies for the confusion.
